# HTTP Server.
[server]
	address        = ":8082"
	serverRoot     = "public"
	serverAgent    = "GoViewFile"
	logPath        = "/tmp/log/GoViewFile/server"
        idleTimeout         = "60s"                        # 仅当Keep-Alive开启时有效，请求闲置时间。默认为60秒
	keepAlive           = true                         # 是否开启Keep-Alive功能。默认true
	routeOverWrite = true

# Logger configurations.
 [logger.access]
        Path        = "./log/GoViewFile"
        Level       = "all"
        Stdout      = true
        CtxKeys     = ["Trace-Id"]
        File        = "access-{Ymd}.log"
[logger.error]
        Path        = "./log/GoViewFile"
        Level       = "all"
        Stdout      = true
        CtxKeys     = ["Trace-Id"]
        File        = "error-{Ymd}.log"

# Template view configurations.
[viewer]
    path        = "template"
    defaultFile = "index.html"


